title: Victoria's Blog
logo: /assets/img/logo.png
email: developer.ssu.ssu@gmail.com
description: 개발 일기
show_downloads: false
google_analytics: UA-108144808-1
remote_theme: BDHU/minimalist
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

sidebar:
  - name: 타사이트로 이동
    link: ./basic-page.html
  - name:  
  - name: GitHub
    icon: fa-brands fa-github
    link: https://github.com/victoriassu
  - name: Blog
    icon: fa-solid fa-pen
    link: https://victoriassu.github.io/
  - name: Project Repository
    icon: fa-solid fa-box-archive
    link: https://github.com/BDHU/minimalist
